baseURL = "https://tanomitech.com/"
languageCode = "en-us"
theme="tailbliss"
title = "Tanomi Technologies"

ignoreFiles = ['(blog|news)-post-\d+.md']

[markup]
  [markup.highlight]
    codeFences = true
    noClasses = false

[params]
  # In most cases you will only want to use either one of these. If you have Google Analytics included in your GTM tags don't put your GA ID here. Otherwise your data might be useless.
  google_analytics_id = ""
  google_tag_manager_id = ""
  moto = "Building technology with trust in mind."
  description = ""
  Disable_stay_uptodate = true
  main_cta_text = "Reach out to us"
  main_cta_link = "mailto: info@tanomitech.com"
  [params.homepage]
    show_call_box = true
    services_heading = "What we can help you with"
    hide_view_all_services = false  # set to true to hide the View All Services button

  [params.logo]
    mobile = "images/logo/logo-alt-mobile.png"
    desktop = "images/logo/logo-alt.png"
    desktop_height = "36px"
    alt = "Tanomi Technologies"

  [params.homepage_meta_tags]
    meta_description = "Tanomi Technologies is a software development company focused building reliable software and becoming your trusted partner."
    meta_og_title = "Tanomi Technologies | Technology Consulting"
    meta_og_type = "website"
    meta_og_url = "https://tanomitech.com"
    meta_og_image = "https://tanomitech.com/images/landing-tech.jpg"
    meta_og_description = "Tanomi Technologies is a software development company focused building reliable software and becoming your trusted partner."
    meta_twitter_card = "summary"

  [params.p4]
    heading = "Latest Posts"
    [[params.p4.content]]
      text = "Explore our insights on product, industry updates & much more."

  [params.footer]
    copyright_text = 'Tanomi Technologies'
  
  [params.social_media.github]
      enabled = false
  [params.social_media.facebook]
      enabled = false
  [params.social_media.instagram]
      enabled = false
  [params.social_media.twitter]
      enabled = true
      url = '@tanomitech'

[menu]
  # Main Menu
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.footer]]
    name = "About"
    url = "/about"
    weight = 2
